### ISSUE TITLE
Move IO repos to sgkit

### ISSUE THREAD

**Issue by tomwhite** [pystatgen/sgkit#259]
We've [decided](https://discourse.pystatgen.org/t/20200910-developer-call-notes/96) to move sgkit-{bgen,plink,vcf} to the main sgkit repo. This is an umbrella issue to track tasks. See also discussion in #65 

- [x] Add Windows CI #247 
- [x] Move sgkit-bgen to main sgkit repo #256
- [x] Move sgkit-plink to main sgkit repo #257
- [x] Move sgkit-vcf to main sgkit repo #258

**Comment by hammer** [comment]
Time to close this one out @tomwhite? I think #65 is good to close as well @ravwojdyla but let me know if you feel otherwise.

**Comment by hammer** [comment]
For sure, thanks for the reminder to archive the repos
